export const fieldMap = {
	"fname": "Contact.FirstName",
	"lname": "Contact.LastName",
	"dob": "Contact.Birthdate",
	"language": "Contact.Preferred_Language__c",
	"rstreet": "Contact.MailingStreet",
	"rcity": "Contact.MailingCity",
	"rstate": "Contact.MailingState",
	"rzip": "Contact.MailingPostalCode",
	"remail": "Contact.Home_Email__c",
	"rmobile": "Contact.MobilePhone",
	"sms": "Contact.tdc_tsw__SMS_Opt_out__c",
	"agency_pardot": "Contact.Account_name_Pardot_sync__c",
	"mstreet": "Contact.OtherStreet",
	"mcity": "Contact.OtherCity",
	"mstate": "Contact.OtherState",
	"mzip": "Contact.OtherPostalCode",

	"classification": "Contact.Title",
	"hiredate": "Contact.Hire_Date__c",
	"wemail": "Contact.Work_Email__c",
	"wphone": "Contact.Work_Phone__c",
	"ethnicity": "Contact.Ethnicity__c",
	"lgbtqID": "Contact.LGBTQ_ID__c",
	"transID": "Contact.Trans_ID__c",
	"disabilityID": "Contact.Disability_ID__c",
	"blindID": "Contact.Blind_or_visually_impaired__c",
	"deafID": "Contact.Deaf_or_hearing_impaired__c",
	"gender": "Contact.Gender__c",
	"pronouns": "Contact.Prounoun__c",
	"worksite": "Contact.Worksite_manual_entry_from_webform__c"
	}