export const fieldMap = {
	"Contact.FirstName": "fname",
	"Contact.LastName": "lname",
	"Contact.Birthdate": "dob",
	"Contact.Preferred_Language__c": "language",
	"Contact.MailingStreet": "rstreet",
	"Contact.MailingCity": "rcity",
	"Contact.MailingState": "rstate",
	"Contact.MailingPostalCode": "rzip",
	"Contact.Home_Email__c": "remail",
	"Contact.MobilePhone": "rmobile",
	"Contact.tdc_tsw__SMS_Opt_out__c": "sms",
	"Contact.Account_name_Pardot_sync__c": "agency_pardot",
	"Contact.OtherStreet": "mstreet",
	"Contact.OtherCity": "mcity",
	"Contact.OtherState": "mstate",
	"Contact.OtherPostalCode": "mzip",
	"Contact.Signature__c": "fullname",
	"Contact.termsagree__c": "termsagree",

	"Contact.Title": "classification",
	"Contact.Hire_Date__c": "hiredate",
	"Contact.Work_Email__c": "wemail",
	"Contact.Work_Phone__c": "wphone",
	"Contact.Ethnicity__c": "ethnicity",
	"Contact.LGBTQ_ID__c": "lgbtqID",
	"Contact.Trans_ID__c": "transID",
	"Contact.Disability_ID__c": "disabilityID",
	"Contact.Blind_or_visually_impaired__c": "blindID",
	"Contact.Deaf_or_hearing_impaired__c": "deafID",
	"Contact.Gender__c": "gender",
	"Contact.Prounoun__c": "pronouns",
	"Contact.Worksite_manual_entry_from_webform__c": "worksite",
	}